const clubes = [
    'Academia Tocalli',
    'Acassuso',
    'Afalp',
    'Agropecuario',
    'Alamos Troncos',
    'Aldosivi',
    'All Boys',
    'Almagro',
    'Almirante Brown',
    'Alvarado',
    'AMERICA FUTBOL CLUB',
    'Argentino (Q)',
    'Argentinos',
    'ARGENTINOS DE DEL VISO',
    'Arquitectura',
    'Arsenal',
    'ASOC. ATL. MATHEU',
    'Asturiano',
    'AT ABROJAL DE PILAR',
    'AT CAZA Y PESCA',
    'ATL. PILAR',
    'Atlanta',
    'Atlanta',
    'Atlético Rafaela',
    'Atlético Rafaela',
    'Atlético Tucumán',
    'Banco Ciudad',
    'Banco Nacion',
    'Banco Provincia',
    'Banfield',
    'Barkojba',
    'Barracas Central',
    'Belgrano',
    'Benavidez Ranch Sports',
    'Boca',
    'Brown de Adrogué',
    'C.S.H.A',
    'C.S.P.F.A FUTBOL',
    'Cañuelas',
    'Central Córdoba',
    'Chacarita Juniors',
    'Chaco For Ever',
    'Chasqui',
    'Cissab',
    'CLUB ATLETICO BOULOGNE',
    'Club Atlético Güemes',
    'Club Brit Ajim',
    'CLUB LOS ANDES',
    'Club Venecia',
    'Colegiales',
    'Colón',
    'Comunicaciones',
    'CPCECABA',
    'D10 FC',
    'DEF.SAVIO',
    'Defensa y Justicia',
    'Defensores de Belgrano',
    'Defensores Unidos',
    'Dep. Armenio',
    'Dep. Santa María',
    'Deportivo Madryn',
    'Deportivo Maipú',
    'Deportivo Morón',
    'Deportivo Riestra',
    'Dock Sud',
    'El Nacional',
    'Escobar Futbol Club',
    'Estudiantes',
    'Estudiantes Caseros',
    'Estudiantes Río Cuarto',
    'Fenix',
    'Ferro Carril Oeste',
    'Flandria',
    'Flandria',
    'Galicia',
    'GEBA',
    'Gimnasia',
    'Gimnasia Jujuy',
    'Gimnasia Mendoza',
    'Godoy Cruz',
    'Guillermo Brown',
    'Harrods',
    'Hebraica',
    'Huracán',
    'Hurlingham',
    'Independiente',
    'Independiente Rivadavia',
    'Ingenieria',
    'Instituto',
    'Italiano',
    'Ituzaingo',
    'JPH Lions',
    'La Negra',
    'La Plata',
    'La Renata',
    'La Salle',
    'Lamroth Hakol',
    'Lanús',
    'Libertador',
    'Liniers',
    'Liniers Norte',
    'Los Andes',
    'Los Molinos',
    'Macabi',
    'Melmac',
    'Merlo',
    'Mitre',
    'Mitre Santiago d. Estero',
    'Naútico HACOAJ',
    'Newell’s',
    'Nordelta',
    'Nueva Chicago',
    'Nueva Chicago',
    'Once Corazones',
    'Patronato',
    'Patronato',
    'PEÑAROL',
    'Pirañas',
    'Platense',
    'Play Futbol FC',
    'POL. GARIN',
    'POL. GRAND BOURG',
    'POLIDEPORTIVO DERQUI',
    'POLIDEPORTIVO ING.MASCHWITZ',
    'Porteño',
    'Quilmes',
    'Quilmes',
    'Racing',
    'Racing Córdoba',
    'RADIO DON TORCUATO',
    'Regatas',
    'Rep. del Oeste',
    'Retiro',
    'Rhino',
    'River',
    'Roma',
    'Roma FC',
    'Rosario Central',
    'RUTA 27 Y TOSCANELLI',
    'S.J. UNION DEL VISO',
    'Sacachispas',
    'San Carlos',
    'San Fernando',
    'San Lorenzo',
    'San Martín San Juan',
    'San Martín Tucumán',
    'San Miguel',
    'San Telmo',
    'San Telmo',
    'Santa Alicia',
    'Santa Barbara',
    'Sarmiento',
    'Sholem',
    'Sitas',
    'SOCIAL MALVINAS ARG.',
    'SOCIEDAD DE FOMENTO NOGUES SUR',
    'SOCIEDAD DE FOMUENTO EL OMBU',
    'SP. ESCOBAR',
    'SP. JOSE C. PAZ',
    'SPORTIVO PILAR FC',
    'Talleres',
    'Talleres (RdE)',
    'Temperley',
    'Temperley',
    'Tigre',
    'Tigres de Moreno',
    'Tigres Moreno',
    'TORO',
    'Tristán Suárez',
    'Trovador',
    'UAI Urquiza',
    'UBA',
    'Unión',
    'Universidad Torcuato di Tella',
    'UNLAM',
    'UTN FRLP',
    'Viajantes',
    'Villa Dálmine',
    'Villa Dálmine',
    'Villa San Carlos',
    'VILLA VALLIER S.F.',
    'Vilo',
]

export default clubes;