const clubesLIGAESCOBARENSE = [
    'Almirante Brown',  
    'Alvarado', 
    'Alvarado', 
    'Atlanta',  
    'Atlanta',  
    'Atlético Rafaela', 
    'Atlético Rafaela', 
    'Brown de Adrogué', 
    'Brown de Adrogué', 
    'Chacarita Juniors',    
    'Chacarita Juniors',    
    'Chaco For Ever',   
    'Chaco For Ever',   
    'Club Atlético Güemes', 
    'Club Atlético Güemes', 
    'Defensores de Belgrano',   
    'Defensores de Belgrano',   
    'Defensores Unidos',    
    'Defensores Unidos',    
    'Deportivo Madryn', 
    'Deportivo Madryn', 
    'Deportivo Maipú',  
    'Deportivo Maipú',  
    'Deportivo Morón',  
    'Deportivo Morón',  
    'Deportivo Riestra',    
    'Deportivo Riestra',    
    'Estudiantes Caseros',  
    'Estudiantes Caseros',  
    'Estudiantes Río Cuarto',   
    'Estudiantes Río Cuarto',   
    'Ferro Carril Oeste',   
    'Ferro Carril Oeste',   
    'Flandria', 
    'Flandria', 
    'Gimnasia Jujuy',   
    'Gimnasia Jujuy',   
    'Gimnasia Mendoza', 
    'Gimnasia Mendoza', 
    'Guillermo Brown',  
    'Guillermo Brown',  
    'Independiente Rivadavia',  
    'Independiente Rivadavia',  
    'Mitre Santiago d. Estero', 
    'Mitre Santiago d. Estero', 
    'Nueva Chicago',    
    'Nueva Chicago',    
    'Patronato',    
    'Patronato',    
    'Quilmes',  
    'Quilmes',  
    'Racing Córdoba',   
    'Racing Córdoba',   
    'San Martín San Juan',  
    'San Martín San Juan',  
    'San Martín Tucumán',   
    'San Martín Tucumán',   
    'San Telmo',    
    'San Telmo',    
    'Temperley',    
    'Temperley',    
    'Tristán Suárez',   
    'Tristán Suárez',   
    'Villa Dálmine',    
    'Villa Dálmine',    
];

export default clubesLIGAESCOBARENSE;