const clubesBMETRO = [
    'Academia Tocalli',
    'Acassuso',
    'Afalp',
    'Alamos Troncos',
    'Arquitectura',
    'Asturiano',
    'Banco Ciudad',
    'Banco Nacion',
    'Banco Provincia',
    'Barkojba',
    'Benavidez Ranch Sports',
    'C.S.H.A',
    'C.S.P.F.A FUTBOL',
    'CPCECABA',
    'Chasqui',
    'Cissab',
    'Club Brit Ajim',
    'Club Venecia',
    'D10 FC',
    'Dep. Santa María',
    'El Nacional',
    'Escobar Futbol Club',
    'GEBA',
    'Galicia',
    'Harrods',
    'Hebraica',
    'Hurlingham',
    'Ingenieria',
    'Italiano',
    'JPH Lions',
    'La Negra',
    'La Plata',
    'La Renata',
    'La Salle',
    'Lamroth Hakol',
    'Libertador',
    'Liniers',
    'Liniers Norte',
    'Los Molinos',
    'Macabi',
    'Melmac',
    'Mitre',
    'Naútico HACOAJ',
    'Nordelta',
    'Once Corazones',
    'Pirañas',
    'Play Futbol FC',
    'Porteño',
    'Regatas',
    'Rep. del Oeste',
    'Retiro',
    'Rhino',
    'Roma',
    'Roma FC',
    'San Carlos',
    'San Fernando',
    'Santa Alicia',
    'Santa Barbara',
    'Sholem',
    'Sitas',
    'Tigres Moreno',
    'Tigres de Moreno',
    'Trovador',
    'UBA',
    'UNLAM',
    'UTN FRLP',
    'Universidad Torcuato di Tella',
    'Viajantes',
    'Vilo',
]

export default clubesBMETRO;