const clubes = [
    "Argentinos",
    "Arsenal",
    "Atlético Tucumán",
    "Banfield",
    "Barracas Central",
    "Belgrano",
    "Boca",
    "Central Córdoba",
    "Colón",
    "Defensa y Justicia",
    "Estudiantes",
    "Gimnasia",
    "Godoy Cruz",
    "Huracán",
    "Independiente",
    "Instituto",
    "Lanús",
    "Newell’s",
    "Platense",
    "Racing",
    "River",
    "Rosario Central",
    "San Lorenzo",
    "Sarmiento",
    "Talleres",
    "Tigre",
    "Unión",
    "Agropecuario",
    "Aldosivi",
    "Aldosivi",
    "All Boys",
    "All Boys",
    "Almagro",
    "Almagro",
    "Almirante Brown",
    "Almirante Brown",
    "Alvarado",
    "Alvarado",
    "Atlanta",
    "Atlanta",
    "Atlético Rafaela",
    "Atlético Rafaela",
    "Brown de Adrogué",
    "Brown de Adrogué",
    "Chacarita Juniors",
    "Chacarita Juniors",
    "Chaco For Ever",
    "Chaco For Ever",
    "Club Atlético Güemes",
    "Club Atlético Güemes",
    "Defensores de Belgrano",
    "Defensores de Belgrano",
    "Defensores Unidos",
    "Defensores Unidos",
    "Deportivo Madryn",
    "Deportivo Madryn",
    "Deportivo Maipú",
    "Deportivo Maipú",
    "Deportivo Morón",
    "Deportivo Morón",
    "Deportivo Riestra",
    "Deportivo Riestra",
    "Estudiantes Caseros",
    "Estudiantes Caseros",
    "Estudiantes Río Cuarto",
    "Estudiantes Río Cuarto",
    "Ferro Carril Oeste",
    "Ferro Carril Oeste",
    "Flandria",
    "Flandria",
    "Gimnasia Jujuy",
    "Gimnasia Jujuy",
    "Gimnasia Mendoza",
    "Gimnasia Mendoza",
    "Guillermo Brown",
    "Guillermo Brown",
    "Independiente Rivadavia",
    "Independiente Rivadavia",
    "Mitre Santiago d. Estero",
    "Mitre Santiago d. Estero",
    "Nueva Chicago",
    "Nueva Chicago",
    "Patronato",
    "Patronato",
    "Quilmes",
    "Quilmes",
    "Racing Córdoba",
    "Racing Córdoba",
    "San Martín San Juan",
    "San Martín San Juan",
    "San Martín Tucumán",
    "San Martín Tucumán",
    "San Telmo",
    "San Telmo",
    "Temperley",
    "Temperley",
    "Tristán Suárez",
    "Tristán Suárez",
    "Villa Dálmine",
    "Villa Dálmine",
    "Acassuso",
    "Argentino (M)",
    "Argentino (Q)",
    "Cañuelas",
    "Colegiales",
    "Comunicaciones",
    "Dep. Armenio",
    "Dock Sud",
    "Fenix",
    "Ituzaingo",
    "Los Andes",
    "Merlo",
    "Sacachispas",
    "San Miguel",
    "Talleres (RdE)",
    "UAI Urquiza",
    "Villa San Carlos",
    "RUTA 27 Y TOSCANELLI",
    "S.J. UNION DEL VISO",
    "AT CAZA Y PESCA",
    "ATL. PILAR",
    "AT ABROJAL DE PILAR",
    "POLIDEPORTIVO ING.MASCHWITZ",
    "CLUB ATLETICO BOULOGNE",
    "SOCIAL MALVINAS ARG.",
    "SOCIEDAD DE FOMENTO NOGUES SUR",
    "AMERICA FUTBOL CLUB",
    "TORO",
    "PEÑAROL",
    "POL. GARIN",
    "RADIO DON TORCUATO",
    "SP. ESCOBAR",
    "SP. JOSE C. PAZ",
    "VILLA VALLIER S.F.",
    "POL. GRAND BOURG",
    "ASOC. ATL. MATHEU",
    "ARGENTINOS DE DEL VISO",
    "DEF.SAVIO",
    "CLUB LOS ANDES",
    "SOCIEDAD DE FOMUENTO EL OMBU",
    "SPORTIVO PILAR FC",
    "POLIDEPORTIVO DERQUI",
    "Academia Tocalli",
    "Acassuso",
    "Afalp",
    "Alamos Troncos",
    "Arquitectura",
    "Asturiano",
    "Banco Ciudad",
    "Banco Nacion",
    "Banco Provincia",
    "Barkojba",
    "Benavidez Ranch Sports",
    "C.S.H.A",
    "C.S.P.F.A FUTBOL",
    "CPCECABA",
    "Chasqui",
    "Cissab",
    "Club Brit Ajim",
    "Club Venecia",
    "D10 FC",
    "Dep. Santa María",
    "El Nacional",
    "Escobar Futbol Club",
    "GEBA",
    "Galicia",
    "Harrods",
    "Hebraica",
    "Hurlingham",
    "Ingenieria",
    "Italiano",
    "JPH Lions",
    "La Negra",
    "La Plata",
    "La Renata",
    "La Salle",
    "Lamroth Hakol",
    "Libertador",
    "Liniers",
    "Liniers Norte",
    "Los Molinos",
    "Macabi",
    "Melmac",
    "Mitre",
    "Naútico HACOAJ",
    "Nordelta",
    "Once Corazones",
    "Pirañas",
    "Play Futbol FC",
    "Porteño",
    "Regatas",
    "Rep. del Oeste",
    "Retiro",
    "Rhino",
    "Roma",
    "Roma FC",
    "San Carlos",
    "San Fernando",
    "Santa Alicia",
    "Santa Barbara",
    "Sholem",
    "Sitas",
    "Tigres Moreno",
    "Tigres de Moreno",
    "Trovador",
    "UBA",
    "UNLAM",
    "UTN FRLP",
    "Universidad Torcuato di Tella",
    "Viajantes",
    "Vilo"
]

export default clubes;